/**
 * Node.js-only auth utilities (uses Node crypto module).
 * Only import in API route handlers — NOT in middleware.ts.
 */

import { createHmac, pbkdf2Sync, randomBytes, timingSafeEqual } from 'crypto';
import { COOKIE_NAME } from './session';

export { COOKIE_NAME };

interface AuthUser {
  username: string;
  salt: string;
  hash: string;
}

/**
 * Reads AUTH_USER_1 … AUTH_USER_3 env vars.
 * Each value must be in the format "username:salt:hash"
 * (generated by scripts/generate-password-hash.mjs).
 */
function getUsers(): AuthUser[] {
  return [
    process.env.AUTH_USER_1,
    process.env.AUTH_USER_2,
    process.env.AUTH_USER_3,
  ]
    .filter(Boolean)
    .map((raw) => {
      const parts = raw!.split(':');
      // username may not contain ':', but salt and hash are hex so they won't
      if (parts.length < 3) return null;
      const hash = parts.pop()!;
      const salt = parts.pop()!;
      const username = parts.join(':');
      return { username, salt, hash };
    })
    .filter(Boolean) as AuthUser[];
}

export function hashPassword(password: string, salt: string): string {
  return pbkdf2Sync(password, salt, 310_000, 32, 'sha256').toString('hex');
}

export function generateSalt(): string {
  return randomBytes(16).toString('hex');
}

/** Constant-time password verification. */
export function verifyPassword(username: string, password: string): boolean {
  const users = getUsers();
  const user = users.find((u) => u.username === username);
  if (!user) return false;

  const computed = Buffer.from(hashPassword(password, user.salt), 'hex');
  const expected = Buffer.from(user.hash, 'hex');
  if (computed.length !== expected.length) return false;
  return timingSafeEqual(computed, expected);
}

const EXPIRY_MS = 30 * 24 * 60 * 60 * 1000; // 30 days

/** Verifies a session token and returns the username, or null if invalid/expired. */
export function verifyToken(token: string): string | null {
  const secret = process.env.SESSION_SECRET;
  if (!secret) return null;

  const dot = token.lastIndexOf('.');
  if (dot === -1) return null;

  const encodedPayload = token.slice(0, dot);
  const encodedSig = token.slice(dot + 1);

  let payload: string;
  let sigBytes: Buffer;
  try {
    payload = Buffer.from(encodedPayload, 'base64url').toString('utf8');
    sigBytes = Buffer.from(encodedSig, 'base64url');
  } catch {
    return null;
  }

  const expectedSig = createHmac('sha256', secret).update(payload).digest();
  if (sigBytes.length !== expectedSig.length || !timingSafeEqual(sigBytes, expectedSig)) return null;

  const colonIdx = payload.lastIndexOf(':');
  if (colonIdx === -1) return null;
  const username = payload.slice(0, colonIdx);
  const issuedAt = parseInt(payload.slice(colonIdx + 1), 10);
  if (isNaN(issuedAt) || Date.now() - issuedAt > EXPIRY_MS) return null;

  return username;
}

/** Creates a signed session token (base64url(payload).base64url(hmac)). */
export function createToken(username: string): string {
  const secret = process.env.SESSION_SECRET;
  if (!secret) throw new Error('SESSION_SECRET is not configured');

  const payload = `${username}:${Date.now()}`;
  const encodedPayload = Buffer.from(payload).toString('base64url');
  const sig = createHmac('sha256', secret).update(payload).digest();
  const encodedSig = sig.toString('base64url');
  return `${encodedPayload}.${encodedSig}`;
}
